### ISSUE TITLE
main page should have a button to "reset" State

### ISSUE THREAD

**Issue by rahulpandita** [rahulpandita/nextjs-sample#18]
Currently there is no way to "reset" the state of the page, including click count and counter value, without reloading the page. There should be a button that lets me reset the state.

**Comment by ptasker** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/gh/rahulpandita/nextjs-sample/issues/18?shareId=62bc2596-ba4e-4f74-bda8-b07a86791726) saved by @ptasker using Copilot Workspace v0.6

<details open><summary><b>Topic</b></summary>
<br/>

Does the main page have a button to "reset" the state now?

</details>

<details open><summary><b>Before</b></summary>
<br/>

* The main page does not have a button to "reset" the state now.
* The main page is defined in `pages/index.js` and uses components from `components/` directory.
* The state is managed by `useState` and `useCallback` hooks in `pages/index.js` and `components/ClickCount.js`.


</details>
<details open><summary><b>After</b></summary>
<br/>

*  The main page has a button to "reset" the state now.
* The main page is defined in `pages/index.js` and uses components from `components/` directory.
* The state is managed by `useState` and `useCallback` hooks in `pages/index.js` and `components/ClickCount.js`.
* The button is imported from `components/Button.js` and styled by `components/Button.module.css`.
* The button has a label of "Reset State" and is placed below the last `<hr>` element in `pages/index.js`.
* The button has an `onClick` handler that sets the `count` state in `pages/index.js` to 0 and calls the `setCount` function from `components/ClickCount.js` with 0 as an argument.


</details>

<details open><summary><b>Plan</b></summary>
<br/>

* Import `Button` component from `components/Button.js` in `pages/index.js`
* Import `setCount` function from `components/ClickCount.js` in `pages/index.js`
* Define a `reset` function in `pages/index.js` that sets the `count` state to 0 and calls `setCount` with 0
* Add a `<Button>` element in `pages/index.js` with a label of "Reset State" and an `onClick` handler of `reset`
* Place the `<Button>` element below the last `<hr>` element in `pages/index.js`




</details>

<details open><summary><b>Files to change, add or remove</b></summary>
<br/>

* `pages/index.js` (CHANGE)


</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

An implementation sketch has not been generated or was not included

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at 22252779ca5edc036bfa171bd67325010e4f3c73

</details>

**Comment by ptasker** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/gh/rahulpandita/nextjs-sample/issues/18?shareId=2c9fbc09-2687-4c13-8994-5ab9785a6c3b) saved by @ptasker using Copilot Workspace v0.6

<details open><summary><b>Topic</b></summary>
<br/>

Does the main page have a button to "reset" State that clears all the user inputs and selections?

</details>

<details open><summary><b>Before</b></summary>
<br/>

* The main page does not have a button to "reset" State.
* The main page is defined in `pages/index.js` and uses several components and styles.
* The only buttons on the main page are for incrementing and throwing errors.


</details>
<details open><summary><b>After</b></summary>
<br/>

*  The main page has a button to "reset" State that clears all the user inputs and selections.
* The main page is defined in `pages/index.js` and uses several components and styles.
* The reset button is added below the last `<hr>` element in the main page.
* The reset button uses the `Button` component from `components/Button.js` and passes a `onClick` prop that resets the state of the `count` and `ClickCount` components.
* The reset button has a label of "Reset State".


</details>

<details open><summary><b>Plan</b></summary>
<br/>

* Import `useState` and `useCallback` from `react` in `pages/index.js`
* Define a new state variable `reset` and a setter function `setReset` in the `Home` component using `useState`
* Pass the `reset` state as a prop to the `ClickCount` component
* Modify the `ClickCount` component in `components/ClickCount.js` to accept the `reset` prop and use it to reset its own state
* Define a new function `handleReset` in the `Home` component using `useCallback` that sets the `count` and `reset` states to zero
* Add a new `<div>` element after the last `<hr>` element in the `Home` component
* Add a new `Button` component inside the `<div>` element with the label "Reset State" and the `onClick` prop set to `handleReset`
* Test the functionality of the reset button and the fast refresh feature




</details>

<details open><summary><b>Files to change, add or remove</b></summary>
<br/>

* `pages/index.js` (CHANGE)
* `components/ClickCount.js` (CHANGE)


</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/gh/rahulpandita/nextjs-sample/issues/18?shareId=2c9fbc09-2687-4c13-8994-5ab9785a6c3b)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at 22252779ca5edc036bfa171bd67325010e4f3c73

</details>
